# Generated by Django 5.0.14 on 2025-10-02 19:09

import django.core.validators
from django.db import migrations, models


def migrate_display_name_to_reserved_username(apps, schema_editor):
    """Migrate existing display_name values to reserved_username (lowercased)"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        if user.display_name:
            # Convert to lowercase and check if it's alphanumeric
            username = user.display_name.lower()
            if username.isalnum():
                user.reserved_username = username
                user.save(update_fields=['reserved_username'])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # Step 1: Add new field (nullable, not unique yet)
        migrations.AddField(
            model_name="user",
            name="reserved_username",
            field=models.CharField(
                blank=True,
                help_text="Optional reserved username (alphanumeric only, no spaces or special characters)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_reserved_username",
                        message="Reserved username must contain only alphanumeric characters (a-z, A-Z, 0-9)",
                        regex="^[a-zA-Z0-9]+$",
                    )
                ],
            ),
        ),
        # Step 2: Migrate data
        migrations.RunPython(migrate_display_name_to_reserved_username, reverse_code=migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="user",
            name="reserved_username",
            field=models.CharField(
                blank=True,
                help_text="Optional reserved username (alphanumeric only, no spaces or special characters)",
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_reserved_username",
                        message="Reserved username must contain only alphanumeric characters (a-z, A-Z, 0-9)",
                        regex="^[a-zA-Z0-9]+$",
                    )
                ],
            ),
        ),
        # Step 4: Remove old field
        migrations.RemoveField(
            model_name="user",
            name="display_name",
        ),
    ]
