# Generated by Django 5.0.14 on 2026-02-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_display_name_to_reserved_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL to user avatar image (stored in S3 or local storage)', max_length=500, null=True),
        ),
    ]
