# Generated by Django 5.0.14 on 2026-03-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_avatar_url_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="seen_intros",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Feature intros the user has dismissed",
            ),
        ),
    ]
