services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chatpop_postgres
    environment:
      POSTGRES_DB: chatpop
      POSTGRES_USER: chatpop_user
      POSTGRES_PASSWORD: chatpop_pass
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatpop_user -d chatpop"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: chatpop_redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
