# Generated by Django 5.0.14 on 2025-10-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_analysis", "0003_add_caption_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoanalysis",
            name="selected_at",
            field=models.DateTimeField(
                blank=True, help_text="When user selected a suggestion", null=True
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="selected_suggestion_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Chat code user selected (e.g., 'bar-room')",
                max_length=100,
                null=True,
            ),
        ),
    ]
