# Generated by Django 5.0.14 on 2025-10-23 08:58

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_analysis", "0005_photoanalysis_caption_embedding_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photoanalysis",
            name="embedding_generated_at",
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_embedding_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when caption embedding was generated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="suggestions_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Conversational/Topic embedding for finding similar chat rooms (text-embedding-3-small, 1536d)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="suggestions_embedding_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when suggestions embedding was generated",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photoanalysis",
            name="caption_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Semantic/Content embedding for broad categorization (text-embedding-3-small, 1536d)",
                null=True,
            ),
        ),
    ]
