# Generated by Django 5.0.14 on 2025-10-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_analysis", "0006_remove_photoanalysis_embedding_generated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoanalysis",
            name="caption_category",
            field=models.CharField(
                blank=True,
                help_text="Category classification of the image",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photoanalysis",
            name="caption_full",
            field=models.TextField(
                blank=True,
                help_text="Full semantic caption used for embedding generation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photoanalysis",
            name="caption_model",
            field=models.CharField(
                blank=True,
                help_text="AI model used for caption generation (e.g., gpt-4o-mini)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photoanalysis",
            name="caption_title",
            field=models.CharField(
                blank=True,
                help_text="Short title extracted from image",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photoanalysis",
            name="caption_visible_text",
            field=models.TextField(
                blank=True,
                help_text="Visible text, labels, or brand names in the image",
                null=True,
            ),
        ),
    ]
