# Generated by Django 5.0.14 on 2025-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_analysis", "0007_alter_photoanalysis_caption_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoanalysis",
            name="seed_suggestions",
            field=models.JSONField(
                blank=True,
                help_text="Initial 10 AI suggestions before refinement (audit trail)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="photoanalysis",
            name="suggestions",
            field=models.JSONField(
                help_text="Refined chat name suggestions (used for display and embeddings)"
            ),
        ),
    ]
