# Generated by Django 5.0.14 on 2025-10-22 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Enable pgvector extension for vector similarity search
        CreateExtension("vector"),
        migrations.CreateModel(
            name="PhotoAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_phash",
                    models.CharField(
                        db_index=True,
                        help_text="Perceptual hash (pHash) for detecting similar images",
                        max_length=64,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="MD5 hash for exact file match detection",
                        max_length=64,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Storage path (S3 or local media directory)",
                        max_length=512,
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("s3", "S3"), ("local", "Local")],
                        default="local",
                        help_text="Where the image is stored",
                        max_length=10,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When to delete the image (null = never)",
                        null=True,
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(help_text="AI-generated chat name suggestions"),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="Complete API response for debugging/reprocessing",
                        null=True,
                    ),
                ),
                (
                    "ai_vision_model",
                    models.CharField(
                        default="gpt-4o",
                        help_text="AI vision model used for analysis (e.g., gpt-4o, claude-3-opus)",
                        max_length=100,
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        help_text="API token usage for cost tracking",
                        null=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Browser fingerprint for tracking anonymous users",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        help_text="IP address for rate limiting",
                        null=True,
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many chats were created from these suggestions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user who uploaded the photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Analysis",
                "verbose_name_plural": "Photo Analyses",
                "db_table": "media_analysis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["image_phash", "created_at"],
                        name="photo_analy_image_p_ca8d79_idx",
                    ),
                    models.Index(
                        fields=["file_hash", "created_at"],
                        name="photo_analy_file_ha_bbb8bd_idx",
                    ),
                    models.Index(
                        fields=["fingerprint", "ip_address"],
                        name="photo_analy_fingerp_392230_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="photo_analy_expires_61c2af_idx"
                    ),
                ],
            },
        ),
    ]
