# Generated by Django 5.0.14 on 2025-10-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Category classification of the image",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_full",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full semantic caption used for embedding generation",
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when caption was generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short title extracted from image",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_visible_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Visible text, labels, or brand names in the image",
            ),
        ),
    ]
