# Generated by Django 5.0.14 on 2025-10-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_analysis", "0002_photoanalysis_caption_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="AI model used for caption generation (e.g., gpt-4o-mini)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_raw_response",
            field=models.JSONField(
                blank=True,
                help_text="Complete caption API response for debugging",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_token_usage",
            field=models.JSONField(
                blank=True,
                help_text="Caption API token usage for cost tracking",
                null=True,
            ),
        ),
    ]
