# Generated by Django 5.0.14 on 2025-10-23 08:47

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_analysis", "0004_photoanalysis_selected_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoanalysis",
            name="caption_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Semantic embedding for similarity search (text-embedding-3-small, 1536d)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="photoanalysis",
            name="embedding_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when embedding was generated",
                null=True,
            ),
        ),
    ]
