# Generated by Django 5.0.14 on 2025-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0008_add_seed_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_category',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_embedding',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_embedding_generated_at',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_full',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_generated_at',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_model',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_raw_response',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_title',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_token_usage',
        ),
        migrations.RemoveField(
            model_name='photoanalysis',
            name='caption_visible_text',
        ),
        migrations.AlterField(
            model_name='photoanalysis',
            name='seed_suggestions',
            field=models.JSONField(blank=True, help_text='Initial 10 AI suggestions from Vision API (audit trail)', null=True),
        ),
    ]
