# Generated by Django 5.0.14 on 2025-11-01 21:38

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_analysis", "0009_remove_photoanalysis_caption_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Display name (e.g., 'Cheers!', 'Happy Hour')",
                        max_length=255,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., 'cheers', 'happy-hour')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description from Vision API"
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1536,
                        help_text="Embedding for suggestion-to-suggestion K-NN matching",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=1,
                        help_text="How many photos generated this suggestion",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Last time this suggestion was used",
                    ),
                ),
                (
                    "is_proper_noun",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Proper nouns (brands, titles) are never matched",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Suggestion",
                "verbose_name_plural": "Suggestions",
                "db_table": "suggestion",
                "ordering": ["-usage_count", "-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["-usage_count", "-last_used_at"],
                        name="suggestion_usage_c_b88f8a_idx",
                    ),
                    models.Index(fields=["key"], name="suggestion_key_b28a54_idx"),
                    models.Index(
                        fields=["is_proper_noun"], name="suggestion_is_prop_2af46f_idx"
                    ),
                ],
            },
        ),
    ]
