# Generated by Django 5.0.14 on 2025-11-01 22:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media_analysis", "0010_add_suggestion_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Embedding for suggestion-to-suggestion K-NN matching (NULL for proper nouns)",
                null=True,
            ),
        ),
    ]
