# Generated by Django 5.0.14 on 2025-11-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0011_allow_null_embedding_for_proper_nouns'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='photoanalysis',
            new_name='media_analy_image_p_93b27c_idx',
            old_name='photo_analy_image_p_ca8d79_idx',
        ),
        migrations.RenameIndex(
            model_name='photoanalysis',
            new_name='media_analy_file_ha_79b543_idx',
            old_name='photo_analy_file_ha_bbb8bd_idx',
        ),
        migrations.RenameIndex(
            model_name='photoanalysis',
            new_name='media_analy_fingerp_94d80e_idx',
            old_name='photo_analy_fingerp_392230_idx',
        ),
        migrations.RenameIndex(
            model_name='photoanalysis',
            new_name='media_analy_expires_523f02_idx',
            old_name='photo_analy_expires_61c2af_idx',
        ),
    ]
