# Generated by Django 5.0.14 on 2025-11-25 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0012_rename_photo_analy_image_p_ca8d79_idx_media_analy_image_p_93b27c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acr_id', models.CharField(blank=True, db_index=True, help_text="ACRCloud's internal track ID", max_length=255, null=True)),
                ('song_title', models.CharField(help_text='Song title from ACRCloud', max_length=500)),
                ('artist', models.CharField(help_text='Artist name(s) from ACRCloud', max_length=500)),
                ('album', models.CharField(blank=True, default='', help_text='Album name from ACRCloud', max_length=500)),
                ('release_date', models.CharField(blank=True, default='', help_text='Release date/year from ACRCloud', max_length=50)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Track duration in milliseconds', null=True)),
                ('confidence_score', models.PositiveIntegerField(default=0, help_text='ACRCloud confidence score (0-100)')),
                ('spotify_track_id', models.CharField(blank=True, db_index=True, default='', help_text='Spotify track ID for linking', max_length=100)),
                ('youtube_video_id', models.CharField(blank=True, default='', help_text='YouTube video ID for linking', max_length=100)),
                ('raw_response', models.JSONField(blank=True, help_text='Complete ACRCloud API response for debugging', null=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, help_text='Browser fingerprint for tracking anonymous users', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address for rate limiting', null=True)),
                ('selected_suggestion_code', models.CharField(blank=True, db_index=True, help_text="Chat code user selected (e.g., 'taylor-swift')", max_length=100, null=True)),
                ('selected_at', models.DateTimeField(blank=True, help_text='When user selected a suggestion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestions', models.ManyToManyField(blank=True, help_text='Suggestions generated from this music recognition', related_name='music_analyses', to='media_analysis.suggestion')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who recognized the music', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Music Analysis',
                'verbose_name_plural': 'Music Analyses',
                'db_table': 'music_analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['acr_id'], name='music_analy_acr_id_76fdae_idx'), models.Index(fields=['spotify_track_id'], name='music_analy_spotify_bc1ca0_idx'), models.Index(fields=['fingerprint', 'ip_address'], name='music_analy_fingerp_30c2d8_idx'), models.Index(fields=['artist', 'song_title'], name='music_analy_artist_cbc4e5_idx')],
            },
        ),
    ]
