# Generated by Django 5.0.14 on 2025-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0013_add_music_analysis_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicMetadataCache',
            fields=[
                ('acr_id', models.CharField(help_text="ACRCloud's internal track ID (primary key for cache lookup)", max_length=255, primary_key=True, serialize=False)),
                ('song_title', models.CharField(help_text='Song title', max_length=500)),
                ('artist', models.CharField(help_text='Artist name(s)', max_length=500)),
                ('genres', models.JSONField(blank=True, default=list, help_text="List of genre strings, e.g., ['Pop', 'Dance']")),
                ('raw_metadata', models.JSONField(blank=True, help_text='Complete ACRCloud Metadata API response', null=True)),
                ('lookup_count', models.PositiveIntegerField(default=1, help_text='Number of times this cache entry was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Music Metadata Cache',
                'verbose_name_plural': 'Music Metadata Cache',
                'db_table': 'music_metadata_cache',
            },
        ),
    ]
