# Generated by Django 5.0.14 on 2025-12-09 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0014_add_music_metadata_cache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSuggestionsCache',
            fields=[
                ('geohash', models.CharField(help_text='Geohash encoding of lat/lng (primary key for cache lookup)', max_length=12, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(help_text='Center latitude of geohash cell')),
                ('longitude', models.FloatField(help_text='Center longitude of geohash cell')),
                ('city_name', models.CharField(blank=True, default='', help_text='City name from reverse geocoding', max_length=255)),
                ('neighborhood_name', models.CharField(blank=True, default='', help_text='Neighborhood name from reverse geocoding', max_length=255)),
                ('suggestions_data', models.JSONField(help_text='Complete suggestions response (venues, city, neighborhood)')),
                ('lookup_count', models.PositiveIntegerField(default=1, help_text='Number of times this cache entry was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Suggestions Cache',
                'verbose_name_plural': 'Location Suggestions Cache',
                'db_table': 'location_suggestions_cache',
                'indexes': [models.Index(fields=['city_name'], name='location_su_city_na_d64665_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(help_text="User's latitude coordinate")),
                ('longitude', models.FloatField(help_text="User's longitude coordinate")),
                ('geohash', models.CharField(db_index=True, help_text="Geohash of user's location (precision 6)", max_length=12)),
                ('city_name', models.CharField(blank=True, default='', help_text='City name from reverse geocoding', max_length=255)),
                ('neighborhood_name', models.CharField(blank=True, default='', help_text='Neighborhood name from reverse geocoding', max_length=255)),
                ('fingerprint', models.CharField(blank=True, db_index=True, help_text='Browser fingerprint for tracking anonymous users', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address for rate limiting', null=True)),
                ('selected_suggestion_code', models.CharField(blank=True, db_index=True, help_text="Chat code user selected (e.g., 'golden-gate-park')", max_length=100, null=True)),
                ('selected_at', models.DateTimeField(blank=True, help_text='When user selected a suggestion', null=True)),
                ('cache_hit', models.BooleanField(default=False, help_text='Whether this request was served from cache')),
                ('cache_source', models.CharField(blank=True, choices=[('redis', 'Redis'), ('postgresql', 'PostgreSQL'), ('api', 'API')], default='', help_text='Where the data came from', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('suggestions', models.ManyToManyField(blank=True, help_text='Suggestions generated from this location', related_name='location_analyses', to='media_analysis.suggestion')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who requested location suggestions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Analysis',
                'verbose_name_plural': 'Location Analyses',
                'db_table': 'location_analysis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['geohash'], name='location_an_geohash_90f832_idx'), models.Index(fields=['city_name'], name='location_an_city_na_a40e75_idx'), models.Index(fields=['fingerprint', 'ip_address'], name='location_an_fingerp_8a99c2_idx')],
            },
        ),
    ]
