# Generated by Django 5.0.14 on 2025-12-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_analysis', '0015_add_location_suggestions_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsuggestionscache',
            name='geohash',
            field=models.CharField(help_text="Geohash + settings suffix (e.g., 'dpsdqp:r10000:v10')", max_length=32, primary_key=True, serialize=False),
        ),
    ]
