# Generated by Django 5.0.14 on 2026-03-08 13:38

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_analysis', '0001_initial'),  # pgvector extension created here
    ]

    operations = [
        migrations.CreateModel(
            name="ChatTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique theme identifier (e.g., 'dark-mode')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the theme", max_length=100
                    ),
                ),
                (
                    "is_dark_mode",
                    models.BooleanField(
                        default=True, help_text="Whether this is a dark theme"
                    ),
                ),
                (
                    "theme_color_light",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color for light system mode",
                        max_length=7,
                    ),
                ),
                (
                    "theme_color_dark",
                    models.CharField(
                        default="#18181b",
                        help_text="Hex color for dark system mode",
                        max_length=7,
                    ),
                ),
                (
                    "container",
                    models.TextField(help_text="Main container Tailwind classes"),
                ),
                ("header", models.TextField(help_text="Header bar Tailwind classes")),
                (
                    "header_title",
                    models.TextField(help_text="Header title text Tailwind classes"),
                ),
                (
                    "header_title_fade",
                    models.TextField(help_text="Gradient fade for title"),
                ),
                (
                    "header_subtitle",
                    models.TextField(help_text="Subtitle text Tailwind classes"),
                ),
                (
                    "sticky_section",
                    models.TextField(help_text="Sticky messages container classes"),
                ),
                (
                    "messages_area",
                    models.TextField(help_text="Scrollable messages container classes"),
                ),
                (
                    "messages_area_container",
                    models.TextField(
                        default="bg-white",
                        help_text="Background classes for messages area container (parent of pattern layer)",
                    ),
                ),
                (
                    "messages_area_bg",
                    models.TextField(
                        blank=True, help_text="Background pattern/SVG configuration"
                    ),
                ),
                (
                    "host_message",
                    models.TextField(help_text="Regular host message bubble classes"),
                ),
                (
                    "sticky_host_message",
                    models.TextField(help_text="Sticky host message bubble classes"),
                ),
                (
                    "host_text",
                    models.TextField(help_text="Host message text color classes"),
                ),
                (
                    "host_message_fade",
                    models.TextField(help_text="Gradient fade for host messages"),
                ),
                (
                    "pinned_message",
                    models.TextField(help_text="Regular pinned message bubble classes"),
                ),
                (
                    "sticky_pinned_message",
                    models.TextField(help_text="Sticky pinned message bubble classes"),
                ),
                (
                    "pinned_text",
                    models.TextField(help_text="Pinned message text color classes"),
                ),
                (
                    "pinned_message_fade",
                    models.TextField(help_text="Gradient fade for pinned messages"),
                ),
                (
                    "regular_message",
                    models.TextField(help_text="Regular user message bubble classes"),
                ),
                (
                    "regular_text",
                    models.TextField(help_text="Regular message text color classes"),
                ),
                (
                    "my_message",
                    models.TextField(
                        default="max-w-[calc(100%-2.5%-5rem+5px)] rounded-xl px-4 py-2.5 bg-blue-500 shadow-md",
                        help_text="Message bubble classes for current user's own messages",
                    ),
                ),
                (
                    "my_text",
                    models.TextField(
                        default="text-white",
                        help_text="Text color classes for current user's own messages",
                    ),
                ),
                (
                    "voice_message_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styling for other users' voice messages (playButton, playIconColor, waveformActive, waveformInactive)",
                    ),
                ),
                (
                    "my_voice_message_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styling for current user's voice messages",
                    ),
                ),
                (
                    "host_voice_message_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styling for host voice messages",
                    ),
                ),
                (
                    "pinned_voice_message_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styling for pinned voice messages",
                    ),
                ),
                (
                    "filter_button_active",
                    models.TextField(help_text="Active filter button style"),
                ),
                (
                    "filter_button_inactive",
                    models.TextField(help_text="Inactive filter button style"),
                ),
                (
                    "input_area",
                    models.TextField(help_text="Message input container classes"),
                ),
                (
                    "input_field",
                    models.TextField(help_text="Message input field classes"),
                ),
                (
                    "pin_icon_color",
                    models.CharField(
                        default="text-yellow-400",
                        help_text="Tailwind classes for pin icon color",
                        max_length=100,
                    ),
                ),
                (
                    "crown_icon_color",
                    models.CharField(
                        default="text-yellow-400",
                        help_text="Tailwind classes for crown (host) icon color",
                        max_length=100,
                    ),
                ),
                (
                    "badge_icon_color",
                    models.CharField(
                        default="text-blue-400",
                        help_text="Tailwind classes for verified badge icon color",
                        max_length=100,
                    ),
                ),
                (
                    "reply_icon_color",
                    models.CharField(
                        default="text-cyan-400",
                        help_text="Tailwind classes for reply icon color",
                        max_length=100,
                    ),
                ),
                (
                    "reaction_highlight_bg",
                    models.CharField(
                        default="bg-zinc-700",
                        help_text="Background classes for highlighted reaction pill",
                        max_length=100,
                    ),
                ),
                (
                    "reaction_highlight_border",
                    models.CharField(
                        default="border border-zinc-500",
                        help_text="Border classes for highlighted reaction pill",
                        max_length=100,
                    ),
                ),
                (
                    "reaction_highlight_text",
                    models.CharField(
                        default="text-zinc-200",
                        help_text="Text color classes for highlighted reaction count",
                        max_length=100,
                    ),
                ),
                (
                    "avatar_size",
                    models.CharField(
                        blank=True,
                        help_text="Tailwind size classes for avatar (e.g., 'w-10 h-10'). Null = use default",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "avatar_border",
                    models.CharField(
                        blank=True,
                        help_text="Optional border/ring classes (e.g., 'ring-2 ring-zinc-700')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "avatar_spacing",
                    models.CharField(
                        default="mr-3",
                        help_text="Spacing between avatar and message content",
                        max_length=50,
                    ),
                ),
                (
                    "my_username",
                    models.CharField(
                        default="text-xs font-semibold text-white",
                        help_text="Tailwind classes for current user's username",
                        max_length=200,
                    ),
                ),
                (
                    "regular_username",
                    models.CharField(
                        default="text-xs font-semibold text-white",
                        help_text="Tailwind classes for other users' usernames",
                        max_length=200,
                    ),
                ),
                (
                    "host_username",
                    models.CharField(
                        default="text-sm font-semibold",
                        help_text="Tailwind classes for host username (used with host_text for color)",
                        max_length=200,
                    ),
                ),
                (
                    "my_host_username",
                    models.CharField(
                        default="text-sm font-semibold text-red-500",
                        help_text="Tailwind classes for host's own username when viewing their own messages",
                        max_length=200,
                    ),
                ),
                (
                    "pinned_username",
                    models.CharField(
                        default="text-sm font-semibold",
                        help_text="Tailwind classes for pinned message username (used with pinned_text for color)",
                        max_length=200,
                    ),
                ),
                (
                    "sticky_host_username",
                    models.CharField(
                        default="text-sm font-semibold text-white",
                        help_text="Tailwind classes for host username in sticky area",
                        max_length=200,
                    ),
                ),
                (
                    "sticky_pinned_username",
                    models.CharField(
                        default="text-sm font-semibold text-white",
                        help_text="Tailwind classes for pinned message username in sticky area",
                        max_length=200,
                    ),
                ),
                (
                    "my_timestamp",
                    models.CharField(
                        default="text-xs text-white opacity-60",
                        help_text="Tailwind classes for current user's message timestamp",
                        max_length=200,
                    ),
                ),
                (
                    "regular_timestamp",
                    models.CharField(
                        default="text-xs text-white opacity-60",
                        help_text="Tailwind classes for other users' message timestamp",
                        max_length=200,
                    ),
                ),
                (
                    "host_timestamp",
                    models.CharField(
                        default="text-xs opacity-60",
                        help_text="Tailwind classes for host message timestamp (used with host_text for color)",
                        max_length=200,
                    ),
                ),
                (
                    "pinned_timestamp",
                    models.CharField(
                        default="text-xs opacity-60",
                        help_text="Tailwind classes for pinned message timestamp (used with pinned_text for color)",
                        max_length=200,
                    ),
                ),
                (
                    "reply_preview_container",
                    models.CharField(
                        default="flex items-center justify-between px-4 py-2 bg-gray-100 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700",
                        help_text="Tailwind classes for reply preview container",
                        max_length=300,
                    ),
                ),
                (
                    "reply_preview_icon",
                    models.CharField(
                        default="w-4 h-4 flex-shrink-0 text-blue-500",
                        help_text="Tailwind classes for reply preview icon",
                        max_length=200,
                    ),
                ),
                (
                    "reply_preview_username",
                    models.CharField(
                        default="text-xs font-semibold text-gray-700 dark:text-gray-300",
                        help_text="Tailwind classes for reply preview username",
                        max_length=200,
                    ),
                ),
                (
                    "reply_preview_content",
                    models.CharField(
                        default="text-xs text-gray-600 dark:text-gray-400 truncate",
                        help_text="Tailwind classes for reply preview message content",
                        max_length=200,
                    ),
                ),
                (
                    "reply_preview_close_button",
                    models.CharField(
                        default="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded",
                        help_text="Tailwind classes for reply preview close button",
                        max_length=200,
                    ),
                ),
                (
                    "reply_preview_close_icon",
                    models.CharField(
                        default="w-4 h-4 text-gray-500",
                        help_text="Tailwind classes for reply preview close icon (X)",
                        max_length=200,
                    ),
                ),
                (
                    "modal_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styles for long-press modal and overlays",
                    ),
                ),
                (
                    "emoji_picker_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styles for emoji reaction picker",
                    ),
                ),
                (
                    "gift_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styles for gift message cards",
                    ),
                ),
                (
                    "input_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styles for message input components",
                    ),
                ),
                (
                    "video_player_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styles for video player overlay",
                    ),
                ),
                (
                    "ui_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Styles for misc UI elements",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Theme",
                "verbose_name_plural": "Chat Themes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GiftCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier e.g. 'gift_coffee'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("emoji", models.CharField(help_text="Emoji character", max_length=10)),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "price_cents",
                    models.PositiveIntegerField(help_text="Price in cents"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food & Drink"),
                            ("fun", "Fun"),
                            ("love", "Love"),
                            ("animals", "Animals"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft-disable without removing"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering within category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Catalog Item",
                "verbose_name_plural": "Gift Catalog Items",
                "ordering": ["category", "sort_order", "price_cents"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="URL-safe room identifier (e.g., 'bar-room', 'roberts-storm-chasing-room')",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "User-created (manual)"),
                            ("ai", "AI-generated (collaborative discovery)"),
                        ],
                        default="manual",
                        help_text="How this room was created: manual (user) or ai (photo analysis)",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "name_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=1536,
                        help_text="Embedding of room name and description for suggestion normalization (text-embedding-3-small, 1536d)",
                        null=True,
                    ),
                ),
                (
                    "access_mode",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True,
                        help_text="Required for private rooms",
                        max_length=50,
                    ),
                ),
                ("voice_enabled", models.BooleanField(default=False)),
                ("video_enabled", models.BooleanField(default=False)),
                ("photo_enabled", models.BooleanField(default=True)),
                (
                    "theme_locked",
                    models.BooleanField(
                        default=False,
                        help_text="If true, users cannot override the theme",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate for location-based discovery",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate for location-based discovery",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "discovery_radius_miles",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum distance in miles for this chat to be discoverable",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        help_text="Theme for this chat room",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_rooms",
                        to="chats.chattheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Browser fingerprint - primary for anonymous, stored for logged-in",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username chosen for this chat (locked)",
                        max_length=100,
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to avatar image for this chat participation (stored in S3 or local storage)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "seen_intros",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature intros dismissed by anonymous user in this chat",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Last known IP address", null=True
                    ),
                ),
                ("first_joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="For future cleanup of inactive users"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logged-in users: primary identifier",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's preferred theme override (only if chat.theme_locked=False)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preferences",
                        to="chats.chattheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="AnonymousUserFingerprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Browser fingerprint hash",
                        max_length=255,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username associated with this fingerprint",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Last known IP address", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this fingerprint was used"
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fingerprints",
                        to="chats.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="Display name in chat", max_length=100),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("host", "Host Message"),
                            ("system", "System Message"),
                            ("gift", "Gift Message"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "voice_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to voice message audio file",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "voice_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Duration of voice message in seconds",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "voice_waveform",
                    models.JSONField(
                        blank=True,
                        help_text="Waveform amplitude data as array of floats (0-1)",
                        null=True,
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to photo file",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "photo_width",
                    models.IntegerField(
                        blank=True, help_text="Photo width in pixels", null=True
                    ),
                ),
                (
                    "photo_height",
                    models.IntegerField(
                        blank=True, help_text="Photo height in pixels", null=True
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to video file",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "video_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Duration of video in seconds",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "video_thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to video thumbnail image",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "video_width",
                    models.IntegerField(
                        blank=True, help_text="Video width in pixels", null=True
                    ),
                ),
                (
                    "video_height",
                    models.IntegerField(
                        blank=True, help_text="Video height in pixels", null=True
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("pinned_at", models.DateTimeField(blank=True, null=True)),
                ("sticky_until", models.DateTimeField(blank=True, null=True)),
                (
                    "pin_amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "current_pin_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "gift_recipient",
                    models.CharField(
                        blank=True,
                        help_text="Recipient username for gift messages (denormalized for filter indexing)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_gift_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Message this is replying to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chats.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: registered user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gift_id",
                    models.CharField(
                        help_text="Gift catalog ID at send time", max_length=50
                    ),
                ),
                ("emoji", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("price_cents", models.PositiveIntegerField()),
                ("sender_username", models.CharField(max_length=100)),
                ("recipient_username", models.CharField(max_length=100)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gift_catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_gifts",
                        to="chats.giftcatalogitem",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift",
                        to="chats.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("emoji", models.CharField(help_text="Emoji character", max_length=10)),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Anonymous user fingerprint",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username at time of reaction", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chats.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logged-in user who reacted",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteBan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "banned_ip_address",
                    models.GenericIPAddressField(
                        blank=True, db_index=True, help_text="IP address ban", null=True
                    ),
                ),
                (
                    "banned_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Browser fingerprint ban",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the ban")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the ban expires (null = permanent)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether ban is currently active"
                    ),
                ),
                (
                    "banned_by",
                    models.ForeignKey(
                        help_text="Staff member who issued the ban",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_bans_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "banned_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered user account ban",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Ban",
                "verbose_name_plural": "Site Bans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("pin", "Message Pin"),
                            ("tip", "Tip to Host"),
                            ("gift", "Gift"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_charge_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="chats.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: registered user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blocked_username",
                    models.CharField(
                        db_index=True,
                        help_text="Username being blocked (case-sensitive)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocker",
                    models.ForeignKey(
                        help_text="Registered user who is blocking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blocked_username",
                    models.CharField(
                        blank=True,
                        help_text="Case-insensitive username block",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "blocked_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Browser fingerprint block",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "blocked_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address for tracking (future: may be used for blocking)",
                        null=True,
                    ),
                ),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Optional note for host"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional: for timed blocks", null=True
                    ),
                ),
                (
                    "blocked_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered user account block",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        help_text="Who created the block (usually host)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_created",
                        to="chats.chatparticipation",
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="chats.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-blocked_at"],
                "indexes": [
                    models.Index(
                        fields=["chat_room", "blocked_username"],
                        name="chats_chatb_chat_ro_315033_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "blocked_fingerprint"],
                        name="chats_chatb_chat_ro_73b503_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "blocked_user"],
                        name="chats_chatb_chat_ro_0f92c8_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="chats_chatb_expires_13b38b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="chatblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blocked_username__isnull", False)),
                fields=("chat_room", "blocked_username"),
                name="unique_chat_username_block",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blocked_fingerprint__isnull", False)),
                fields=("chat_room", "blocked_fingerprint"),
                name="unique_chat_fingerprint_block",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blocked_user__isnull", False)),
                fields=("chat_room", "blocked_user"),
                name="unique_chat_user_block",
            ),
        ),
        migrations.AddIndex(
            model_name="anonymoususerfingerprint",
            index=models.Index(
                fields=["fingerprint", "chat_room"],
                name="chats_anony_fingerp_903e5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anonymoususerfingerprint",
            index=models.Index(
                fields=["chat_room", "-last_seen"],
                name="chats_anony_chat_ro_fdaa2c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="anonymoususerfingerprint",
            unique_together={("chat_room", "fingerprint")},
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["code", "source"], name="chats_chatr_code_7ce957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["host", "code"], name="chats_chatr_host_id_270e28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["created_at"], name="chats_chatr_created_cdb00e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "manual")),
                fields=("host", "code"),
                name="unique_manual_room_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "ai")),
                fields=("code",),
                name="unique_ai_room_global",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipation",
            index=models.Index(
                fields=["chat_room", "user"], name="chats_chatp_chat_ro_8590c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipation",
            index=models.Index(
                fields=["chat_room", "fingerprint"],
                name="chats_chatp_chat_ro_5be7be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipation",
            index=models.Index(
                fields=["chat_room", "username"], name="chats_chatp_chat_ro_58abc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipation",
            index=models.Index(
                fields=["-last_seen_at"], name="chats_chatp_last_se_8198f3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatparticipation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("chat_room", "user"),
                name="unique_chat_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatparticipation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("chat_room", "fingerprint"),
                name="unique_chat_fingerprint",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat_room", "-created_at"],
                name="chats_messa_chat_ro_b19084_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat_room", "is_pinned", "-pinned_at"],
                name="chats_messa_chat_ro_b81b02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gift",
            index=models.Index(
                fields=["recipient_username", "chat_room", "is_acknowledged"],
                name="chats_gift_recipie_bf46f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gift",
            index=models.Index(
                fields=["chat_room", "-created_at"],
                name="chats_gift_chat_ro_8ebf26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "emoji"], name="chats_messa_message_470e59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "user", "emoji"],
                name="chats_messa_message_7d9fbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "fingerprint", "emoji"],
                name="chats_messa_message_3cccfb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("message", "user", "emoji"),
                name="unique_message_user_emoji_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("message", "fingerprint", "emoji"),
                name="unique_message_fingerprint_emoji_reaction",
            ),
        ),
        migrations.AddIndex(
            model_name="siteban",
            index=models.Index(
                fields=["banned_user"], name="chats_siteb_banned__a46237_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteban",
            index=models.Index(
                fields=["banned_ip_address"], name="chats_siteb_banned__6f7dee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteban",
            index=models.Index(
                fields=["banned_fingerprint"], name="chats_siteb_banned__b2c338_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="siteban",
            index=models.Index(
                fields=["is_active", "expires_at"],
                name="chats_siteb_is_acti_dacbd8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["chat_room", "-created_at"],
                name="chats_trans_chat_ro_8c566c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="chats_trans_stripe__e6c5d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userblock",
            index=models.Index(
                fields=["blocker", "blocked_username"],
                name="chats_userb_blocker_58b17f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userblock",
            unique_together={("blocker", "blocked_username")},
        ),
    ]
