# Generated by Django 5.0.14 on 2026-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_from_host",
            field=models.BooleanField(
                default=False,
                help_text="Whether this message was sent by the chat room host (using registered identity)",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("system", "System Message"),
                    ("gift", "Gift Message"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
