# Generated by Django 5.0.14 on 2025-10-01 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Message this is replying to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="chats.message",
            ),
        ),
    ]
