# Generated by Django 5.0.14 on 2025-10-01 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_message_reply_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousUserFingerprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Browser fingerprint hash",
                        max_length=255,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username associated with this fingerprint",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this fingerprint was used"
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fingerprints",
                        to="chats.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["fingerprint", "chat_room"],
                        name="chats_anony_fingerp_903e5e_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "-last_seen"],
                        name="chats_anony_chat_ro_fdaa2c_idx",
                    ),
                ],
                "unique_together": {("chat_room", "fingerprint")},
            },
        ),
    ]
