# Generated by Django 5.0.14 on 2026-03-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_add_is_from_host_to_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattheme",
            name="broadcast_icon_color",
            field=models.CharField(
                default="text-blue-400",
                help_text="Tailwind classes for broadcast icon color",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_broadcast",
            field=models.BooleanField(default=False),
        ),
    ]
