# Generated by Django 5.0.14 on 2025-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_anonymoususerfingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymoususerfingerprint",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="Last known IP address", null=True
            ),
        ),
    ]
