# Generated by Django 5.0.14 on 2026-03-29 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_add_broadcast_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousPIN",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Browser fingerprint hash",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "pin_hash",
                    models.CharField(
                        help_text="Hashed PIN using Django's make_password",
                        max_length=256,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Anonymous PIN",
                "verbose_name_plural": "Anonymous PINs",
            },
        ),
    ]
