# Generated by Django 5.0.14 on 2026-04-04 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_anonymouspin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatblock",
            name="ban_tier",
            field=models.CharField(
                choices=[
                    ("session", "Session Ban"),
                    ("fingerprint_ip", "Device + IP Ban"),
                    ("ip", "Total IP Ban"),
                ],
                default="session",
                help_text="Ban enforcement level: session (clearable), fingerprint+IP (device), or IP (network)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatblock",
            name="blocked_session_key",
            field=models.CharField(
                blank=True,
                help_text="Django session key block",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatparticipation",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Django session key - primary identifier for anonymous users",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Django session key - primary identifier for anonymous reactions",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="siteban",
            name="banned_session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Django session key ban",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatblock",
            name="blocked_ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address block", null=True
            ),
        ),
        migrations.AlterField(
            model_name="chatparticipation",
            name="fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Browser fingerprint - stored for ban enforcement only",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="messagereaction",
            name="fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Anonymous user fingerprint (legacy, ban enforcement)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="chatblock",
            index=models.Index(
                fields=["chat_room", "blocked_session_key"],
                name="chats_chatb_chat_ro_a14828_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatblock",
            index=models.Index(
                fields=["chat_room", "ban_tier"], name="chats_chatb_chat_ro_0b59e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipation",
            index=models.Index(
                fields=["chat_room", "session_key"],
                name="chats_chatp_chat_ro_b7d276_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(
                fields=["message", "session_key", "emoji"],
                name="chats_messa_message_caa5f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="siteban",
            index=models.Index(
                fields=["banned_session_key"], name="chats_siteb_banned__6df971_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatparticipation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session_key__isnull", False), ("user__isnull", True)
                ),
                fields=("chat_room", "session_key"),
                name="unique_chat_session_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session_key__isnull", False), ("user__isnull", True)
                ),
                fields=("message", "session_key", "emoji"),
                name="unique_message_session_emoji_reaction",
            ),
        ),
    ]
