# Generated by Django 5.0.14 on 2026-04-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_add_session_key_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatparticipation",
            name="unique_chat_fingerprint",
        ),
    ]
