# Generated by Django 5.0.14 on 2025-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0005_backroommessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="default_theme",
            field=models.CharField(
                default="design1",
                help_text="Default theme for this chat room (design1, design2, design3)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="theme_locked",
            field=models.BooleanField(
                default=False, help_text="If true, users cannot override the theme"
            ),
        ),
    ]
