# Generated by Django 5.0.14 on 2026-04-04 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_remove_unique_chat_fingerprint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousIdentityLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_identity_links",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        help_text="The anonymous ChatParticipation this user owns",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_link",
                        to="chats.chatparticipation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The registered user who owns this anonymous identity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_identity_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Identity Link",
                "verbose_name_plural": "Anonymous Identity Links",
                "indexes": [
                    models.Index(
                        fields=["user", "chat_room"],
                        name="chats_anony_user_id_8a3f4b_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="anonymousidentitylink",
            constraint=models.UniqueConstraint(
                fields=("user", "chat_room"), name="unique_user_chat_anonymous_link"
            ),
        ),
    ]
