# Generated by Django 5.0.14 on 2025-10-03 00:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_chatroom_default_theme_chatroom_theme_locked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatParticipation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Browser fingerprint - primary for anonymous, stored for logged-in",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username chosen for this chat (locked)",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Last known IP address", null=True
                    ),
                ),
                ("first_joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="For future cleanup of inactive users"
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logged-in users: primary identifier",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["chat_room", "user"],
                        name="chats_chatp_chat_ro_8590c6_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "fingerprint"],
                        name="chats_chatp_chat_ro_5be7be_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "username"],
                        name="chats_chatp_chat_ro_58abc2_idx",
                    ),
                    models.Index(
                        fields=["-last_seen_at"], name="chats_chatp_last_se_8198f3_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="chatparticipation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("chat_room", "user"),
                name="unique_chat_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatparticipation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("chat_room", "fingerprint"),
                name="unique_chat_fingerprint",
            ),
        ),
    ]
