# Generated by Django 5.0.14 on 2026-04-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0007_add_anonymous_identity_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnonymousPIN",
        ),
        migrations.DeleteModel(
            name="AnonymousUserFingerprint",
        ),
    ]
