# Generated by Django 5.0.14 on 2025-10-03 00:58

from django.db import migrations


def migrate_fingerprints_to_participation(apps, schema_editor):
    """Migrate AnonymousUserFingerprint records to ChatParticipation"""
    AnonymousUserFingerprint = apps.get_model('chats', 'AnonymousUserFingerprint')
    ChatParticipation = apps.get_model('chats', 'ChatParticipation')

    for fingerprint_record in AnonymousUserFingerprint.objects.all():
        # Create ChatParticipation record for anonymous users
        ChatParticipation.objects.get_or_create(
            chat_room=fingerprint_record.chat_room,
            fingerprint=fingerprint_record.fingerprint,
            user=None,  # Anonymous users have no user
            defaults={
                'username': fingerprint_record.username,
                'ip_address': fingerprint_record.ip_address,
                'first_joined_at': fingerprint_record.created_at,
                'last_seen_at': fingerprint_record.last_seen,
                'is_active': True,
            }
        )


def reverse_migration(apps, schema_editor):
    """Reverse migration - delete ChatParticipation records for anonymous users"""
    ChatParticipation = apps.get_model('chats', 'ChatParticipation')
    # Delete only anonymous user participations (user is null)
    ChatParticipation.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0007_chatparticipation_chatparticipation_unique_chat_user_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_fingerprints_to_participation, reverse_migration),
    ]
