# Generated by Django 5.0.14 on 2025-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0008_migrate_fingerprints_to_participation"),
    ]

    operations = [
        migrations.AddField(
            model_name="backroommessage",
            name="voice_url",
            field=models.URLField(
                blank=True,
                help_text="URL to voice message audio file",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="voice_url",
            field=models.URLField(
                blank=True,
                help_text="URL to voice message audio file",
                max_length=500,
                null=True,
            ),
        ),
    ]
