# Generated by Django 5.0.14 on 2026-04-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0008_drop_anonymous_fingerprint_and_pin"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="messagereaction",
            name="unique_message_fingerprint_emoji_reaction",
        ),
    ]
