# Generated by Django 5.0.14 on 2025-10-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0009_backroommessage_voice_url_message_voice_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="backroommessage",
            name="voice_duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Duration of voice message in seconds",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="backroommessage",
            name="voice_waveform",
            field=models.JSONField(
                blank=True,
                help_text="Waveform amplitude data as array of floats (0-1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="voice_duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Duration of voice message in seconds",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="voice_waveform",
            field=models.JSONField(
                blank=True,
                help_text="Waveform amplitude data as array of floats (0-1)",
                null=True,
            ),
        ),
    ]
