# Generated by Django 5.0.14 on 2026-04-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0009_remove_fingerprint_reaction_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatblock",
            name="unique_chat_fingerprint_block",
        ),
    ]
