# Generated by Django 5.0.14 on 2025-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0010_backroommessage_voice_duration_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="backroommember",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="backroommessage",
            name="back_room",
        ),
        migrations.RemoveField(
            model_name="backroommember",
            name="back_room",
        ),
        migrations.RemoveField(
            model_name="backroommember",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="back_room_member",
        ),
        migrations.RemoveField(
            model_name="backroommessage",
            name="reply_to",
        ),
        migrations.RemoveField(
            model_name="backroommessage",
            name="user",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("pin", "Message Pin"), ("tip", "Tip to Host")], max_length=10
            ),
        ),
        migrations.DeleteModel(
            name="BackRoom",
        ),
        migrations.DeleteModel(
            name="BackRoomMember",
        ),
        migrations.DeleteModel(
            name="BackRoomMessage",
        ),
    ]
