# Generated by Django 5.0.14 on 2026-04-06 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0010_remove_fingerprint_block_uniqueness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="anonymousidentitylink",
            name="unique_user_chat_anonymous_link",
        ),
        migrations.AddConstraint(
            model_name="anonymousidentitylink",
            constraint=models.UniqueConstraint(
                fields=("user", "chat_room", "participation"),
                name="unique_user_chat_participation_anonymous_link",
            ),
        ),
    ]
