# Generated by Django 5.0.14 on 2025-10-06 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0011_remove_backroommessage_back_room_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique theme identifier (e.g., 'dark-mode')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the theme", max_length=100
                    ),
                ),
                (
                    "is_dark_mode",
                    models.BooleanField(
                        default=True, help_text="Whether this is a dark theme"
                    ),
                ),
                (
                    "theme_color_light",
                    models.CharField(
                        default="#ffffff",
                        help_text="Hex color for light system mode",
                        max_length=7,
                    ),
                ),
                (
                    "theme_color_dark",
                    models.CharField(
                        default="#18181b",
                        help_text="Hex color for dark system mode",
                        max_length=7,
                    ),
                ),
                (
                    "container",
                    models.TextField(help_text="Main container Tailwind classes"),
                ),
                ("header", models.TextField(help_text="Header bar Tailwind classes")),
                (
                    "header_title",
                    models.TextField(help_text="Header title text Tailwind classes"),
                ),
                (
                    "header_title_fade",
                    models.TextField(help_text="Gradient fade for title"),
                ),
                (
                    "header_subtitle",
                    models.TextField(help_text="Subtitle text Tailwind classes"),
                ),
                (
                    "sticky_section",
                    models.TextField(help_text="Sticky messages container classes"),
                ),
                (
                    "messages_area",
                    models.TextField(help_text="Scrollable messages container classes"),
                ),
                (
                    "messages_area_bg",
                    models.TextField(
                        blank=True, help_text="Background pattern/SVG configuration"
                    ),
                ),
                (
                    "host_message",
                    models.TextField(help_text="Regular host message bubble classes"),
                ),
                (
                    "sticky_host_message",
                    models.TextField(help_text="Sticky host message bubble classes"),
                ),
                (
                    "host_text",
                    models.TextField(help_text="Host message text color classes"),
                ),
                (
                    "host_message_fade",
                    models.TextField(help_text="Gradient fade for host messages"),
                ),
                (
                    "pinned_message",
                    models.TextField(help_text="Regular pinned message bubble classes"),
                ),
                (
                    "sticky_pinned_message",
                    models.TextField(help_text="Sticky pinned message bubble classes"),
                ),
                (
                    "pinned_text",
                    models.TextField(help_text="Pinned message text color classes"),
                ),
                (
                    "pinned_message_fade",
                    models.TextField(help_text="Gradient fade for pinned messages"),
                ),
                (
                    "regular_message",
                    models.TextField(help_text="Regular user message bubble classes"),
                ),
                (
                    "regular_text",
                    models.TextField(help_text="Regular message text color classes"),
                ),
                (
                    "filter_button_active",
                    models.TextField(help_text="Active filter button style"),
                ),
                (
                    "filter_button_inactive",
                    models.TextField(help_text="Inactive filter button style"),
                ),
                (
                    "input_area",
                    models.TextField(help_text="Message input container classes"),
                ),
                (
                    "input_field",
                    models.TextField(help_text="Message input field classes"),
                ),
                (
                    "background_svg_url",
                    models.CharField(
                        blank=True,
                        help_text="Path to SVG file (e.g., '/bg-pattern.svg')",
                        max_length=255,
                    ),
                ),
                (
                    "background_svg_size",
                    models.CharField(
                        blank=True,
                        help_text="SVG tile size (e.g., '800px 533px')",
                        max_length=100,
                    ),
                ),
                (
                    "background_svg_opacity",
                    models.CharField(
                        blank=True,
                        help_text="Opacity value (e.g., '0.06')",
                        max_length=10,
                    ),
                ),
                (
                    "background_svg_filter",
                    models.TextField(blank=True, help_text="CSS filter string"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Theme",
                "verbose_name_plural": "Chat Themes",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="default_theme",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="theme",
            field=models.ForeignKey(
                help_text="Theme for this chat room",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_rooms",
                to="chats.chattheme",
            ),
        ),
    ]
