# Generated by Django 5.0.14 on 2026-04-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0012_collapse_anonymous_identity_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipation",
            name="is_spotlight",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Host-assigned spotlight status. Spotlighted users get a star icon, 'Spotlight' pill, and appear in the Focus room filter. Per-participation — different identities of the same user are independently spotlighted.",
            ),
        ),
    ]
