# Generated by Django 5.0.14 on 2025-10-06 21:15

from django.db import migrations


def populate_dark_mode_theme(apps, schema_editor):
    """Create the default dark-mode theme with current design values"""
    ChatTheme = apps.get_model('chats', 'ChatTheme')

    ChatTheme.objects.create(
        theme_id='dark-mode',
        name='Dark Mode',
        is_dark_mode=True,
        theme_color_light='#18181b',
        theme_color_dark='#18181b',

        # Layout & Container
        container='h-[100dvh] w-screen max-w-full overflow-x-hidden flex flex-col bg-zinc-950',
        header='border-b border-zinc-800 bg-zinc-900 px-4 py-3 flex-shrink-0',
        header_title='text-lg font-bold text-zinc-100',
        header_title_fade='bg-gradient-to-l from-zinc-900 to-transparent',
        header_subtitle='text-sm text-zinc-400',

        # Messages Area
        sticky_section='absolute top-0 left-0 right-0 z-20 border-b border-zinc-800 bg-zinc-900/90 px-4 py-2 space-y-2 shadow-lg',
        messages_area='absolute inset-0 overflow-y-auto px-4 py-4 space-y-2',
        messages_area_bg="bg-[url('/bg-pattern.svg')] bg-repeat bg-[length:800px_533px] opacity-[0.06] [filter:invert(1)_sepia(1)_hue-rotate(180deg)_saturate(3)]",

        # Host Messages
        host_message='max-w-[calc(100%-2.5%-5rem+5px)] rounded px-3 py-2 bg-cyan-400 font-medium transition-all duration-300',
        sticky_host_message='w-full rounded px-3 py-2 pr-[calc(2.5%+5rem-5px)] bg-cyan-400 font-medium transition-all duration-300',
        host_text='text-cyan-950',
        host_message_fade='bg-gradient-to-l from-cyan-400 to-transparent',

        # Pinned Messages
        pinned_message='max-w-[calc(100%-2.5%-5rem+5px)] rounded px-3 py-2 bg-yellow-400 font-medium transition-all duration-300',
        sticky_pinned_message='w-full rounded px-3 py-2 pr-[calc(2.5%+5rem-5px)] bg-yellow-400 font-medium transition-all duration-300',
        pinned_text='text-yellow-950',
        pinned_message_fade='bg-gradient-to-l from-yellow-400 to-transparent',

        # Regular Messages
        regular_message='max-w-[calc(100%-2.5%-5rem+5px)] rounded px-3 py-2 bg-zinc-800 border-l-2 border-cyan-500/50',
        regular_text='text-zinc-100',

        # Filter Buttons
        filter_button_active='px-3 py-1.5 rounded text-xs tracking-wider bg-cyan-400 text-cyan-950 border border-cyan-300',
        filter_button_inactive='px-3 py-1.5 rounded text-xs tracking-wider bg-zinc-800 text-zinc-400 border border-zinc-700',

        # Input Area
        input_area='border-t border-zinc-800 bg-zinc-900 px-4 py-3 flex-shrink-0',
        input_field='flex-1 px-4 py-2 border border-zinc-700 rounded-lg focus:ring-2 focus:ring-cyan-400 focus:border-transparent bg-zinc-800 text-zinc-100 placeholder-zinc-500',

        # Background SVG
        background_svg_url='/bg-pattern.svg',
        background_svg_size='800px 533px',
        background_svg_opacity='0.06',
        background_svg_filter='invert(1) sepia(1) hue-rotate(180deg) saturate(3)',
    )


def reverse_populate(apps, schema_editor):
    """Remove the dark-mode theme"""
    ChatTheme = apps.get_model('chats', 'ChatTheme')
    ChatTheme.objects.filter(theme_id='dark-mode').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0012_chattheme_remove_chatroom_default_theme_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_dark_mode_theme, reverse_populate),
    ]
