# Generated by Django 5.0.14 on 2025-10-06 21:20

from django.db import migrations


def assign_dark_mode_to_chats(apps, schema_editor):
    """Assign dark-mode theme to all existing chat rooms"""
    ChatRoom = apps.get_model('chats', 'ChatRoom')
    ChatTheme = apps.get_model('chats', 'ChatTheme')

    try:
        dark_mode = ChatTheme.objects.get(theme_id='dark-mode')
        # Update all chat rooms that don't have a theme assigned
        ChatRoom.objects.filter(theme__isnull=True).update(theme=dark_mode)
    except ChatTheme.DoesNotExist:
        pass  # Theme not found, skip


def reverse_assign(apps, schema_editor):
    """Set theme back to null for all chat rooms"""
    ChatRoom = apps.get_model('chats', 'ChatRoom')
    ChatRoom.objects.all().update(theme=None)


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0013_populate_dark_mode_theme"),
    ]

    operations = [
        migrations.RunPython(assign_dark_mode_to_chats, reverse_assign),
    ]
