# Generated by Django 5.0.14 on 2026-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0013_chatparticipation_is_spotlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattheme",
            name="spotlight_icon_color",
            field=models.CharField(
                default="text-yellow-400",
                help_text="Tailwind classes for spotlight star icon and pill colors",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="spotlight_message",
            field=models.TextField(
                default="max-w-[calc(100%-2.5%-5rem+5px)] rounded-xl p-3 bg-[#2a1f05] border border-[#3d2e0a]",
                help_text="Spotlighted user message bubble classes",
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="spotlight_text",
            field=models.TextField(
                default="text-white",
                help_text="Spotlighted user message text color classes",
            ),
        ),
    ]
