# Generated by Django 5.0.14 on 2026-04-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0014_chattheme_spotlight_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="host_pinned_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Host-curated pinned message shown in the top sticky slot. Only one per chat. Set by the host, free (no payment).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="host_pinned_in",
                to="chats.message",
            ),
        ),
    ]
