# Generated by Django 5.0.14 on 2025-10-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0014_assign_theme_to_existing_chats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chattheme",
            name="background_svg_filter",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="background_svg_opacity",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="background_svg_size",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="background_svg_url",
        ),
    ]
