# Generated by Django 5.0.14 on 2026-04-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0016_rename_broadcast_to_highlight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattheme",
            name="highlight_icon_color",
            field=models.CharField(
                default="text-blue-400",
                help_text="Tailwind classes for highlight icon color",
                max_length=100,
            ),
        ),
    ]
