# Generated by Django 5.0.14 on 2026-04-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0017_alter_chattheme_highlight_icon_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="highlighted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the host highlighted this message. Used for ordering the highlight sticky slot.",
                null=True,
            ),
        ),
    ]
