# Generated by Django 5.0.14 on 2025-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0018_update_light_mode_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name='chattheme',
            name='my_message',
            field=models.TextField(
                default='max-w-[calc(100%-2.5%-5rem+5px)] rounded-xl px-4 py-2.5 bg-blue-500 shadow-md',
                help_text="Message bubble classes for current user's own messages"
            ),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='my_text',
            field=models.TextField(
                default='text-white',
                help_text="Text color classes for current user's own messages"
            ),
        ),
    ]
