# Generated by Django 5.0.14 on 2026-04-11 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0018_message_highlighted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="broadcast_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Host-curated broadcast message shown in the top sticky slot. Only one per chat. Set by the host via toggle.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcast_in",
                to="chats.message",
            ),
        ),
    ]
