# Generated by Django 5.0.14 on 2026-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0019_chatroom_broadcast_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipation",
            name="room_last_read",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-room last-read timestamps: {'highlight': '2026-...', 'focus': '2026-...', 'gifts': '2026-...'}",
            ),
        ),
    ]
