# Generated by Django 5.0.14 on 2025-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0020_set_light_mode_my_message_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattheme",
            name="my_voice_play_button",
            field=models.CharField(
                blank=True,
                help_text="Play button background for own voice messages",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="my_voice_play_icon_color",
            field=models.CharField(
                blank=True,
                help_text="Play/pause icon color for own voice messages",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="my_voice_waveform_active",
            field=models.CharField(
                blank=True,
                help_text="Active waveform bars for own voice messages",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="my_voice_waveform_inactive",
            field=models.CharField(
                blank=True,
                help_text="Inactive waveform bars for own voice messages",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="voice_play_button",
            field=models.CharField(
                blank=True,
                help_text="Play button background classes (e.g., 'bg-gradient-to-r from-purple-500 to-blue-500')",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="voice_play_icon_color",
            field=models.CharField(
                blank=True,
                help_text="Play/pause icon color hex (e.g., 'white' or '#3b82f6')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="voice_waveform_active",
            field=models.CharField(
                blank=True,
                help_text="Active waveform bar classes (e.g., 'bg-gradient-to-t from-purple-500 to-blue-500')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="voice_waveform_inactive",
            field=models.CharField(
                blank=True,
                help_text="Inactive waveform bar classes (e.g., 'bg-gray-400')",
                max_length=200,
            ),
        ),
    ]
