# Generated by Django 5.0.14 on 2026-04-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0020_chatparticipation_room_last_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatparticipation",
            name="room_last_read",
        ),
    ]
