# Generated by Django 5.0.14 on 2025-10-08 17:30

from django.db import migrations, models


def migrate_voice_styles_to_json(apps, schema_editor):
    """Convert old CharField voice styles to new JSON structure"""
    ChatTheme = apps.get_model('chats', 'ChatTheme')

    for theme in ChatTheme.objects.all():
        # Migrate regular voice message styles
        theme.voice_message_styles = {
            'playButton': theme.voice_play_button or '',
            'playIconColor': theme.voice_play_icon_color or '',
            'waveformActive': theme.voice_waveform_active or '',
            'waveformInactive': theme.voice_waveform_inactive or '',
        }

        # Migrate "my" voice message styles
        theme.my_voice_message_styles = {
            'playButton': theme.my_voice_play_button or '',
            'playIconColor': theme.my_voice_play_icon_color or '',
            'waveformActive': theme.my_voice_waveform_active or '',
            'waveformInactive': theme.my_voice_waveform_inactive or '',
        }

        # For light themes: host and pinned use "my" styles (white button, blue icons)
        # For dark themes: host and pinned use regular styles (purple-blue gradient)
        if theme.is_dark_mode:
            theme.host_voice_message_styles = theme.voice_message_styles.copy()
            theme.pinned_voice_message_styles = theme.voice_message_styles.copy()
        else:
            theme.host_voice_message_styles = theme.my_voice_message_styles.copy()
            theme.pinned_voice_message_styles = theme.my_voice_message_styles.copy()

        theme.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0021_add_voice_message_styling"),
    ]

    operations = [
        # Step 1: Add new JSON fields
        migrations.AddField(
            model_name="chattheme",
            name="voice_message_styles",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Styling for other users' voice messages (playButton, playIconColor, waveformActive, waveformInactive)",
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="my_voice_message_styles",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Styling for current user's voice messages",
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="host_voice_message_styles",
            field=models.JSONField(
                blank=True, default=dict, help_text="Styling for host voice messages"
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="pinned_voice_message_styles",
            field=models.JSONField(
                blank=True, default=dict, help_text="Styling for pinned voice messages"
            ),
        ),

        # Step 2: Migrate data from old fields to new JSON fields
        migrations.RunPython(migrate_voice_styles_to_json, reverse_code=migrations.RunPython.noop),

        # Step 3: Remove old CharField fields
        migrations.RemoveField(
            model_name="chattheme",
            name="voice_play_button",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="voice_play_icon_color",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="voice_waveform_active",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="voice_waveform_inactive",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="my_voice_play_button",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="my_voice_play_icon_color",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="my_voice_waveform_active",
        ),
        migrations.RemoveField(
            model_name="chattheme",
            name="my_voice_waveform_inactive",
        ),
    ]
