# Generated by Django 5.0.14 on 2025-10-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0022_convert_voice_styles_to_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipation",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                help_text="User's preferred theme override (only if chat.theme_locked=False)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_preferences",
                to="chats.chattheme",
            ),
        ),
    ]
