# Generated by Django 5.0.14 on 2025-10-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0021_set_dark_mode_my_message_blue"),
        ("chats", "0023_chatparticipation_theme"),
    ]

    operations = []
