# Generated by Django 5.0.14 on 2025-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0029_fix_emerald_green_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattheme",
            name="badge_icon_color",
            field=models.CharField(
                default="text-blue-400",
                help_text="Tailwind classes for verified badge icon color",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="crown_icon_color",
            field=models.CharField(
                default="text-yellow-400",
                help_text="Tailwind classes for crown (host) icon color",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="pin_icon_color",
            field=models.CharField(
                default="text-yellow-400",
                help_text="Tailwind classes for pin icon color",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="reply_icon_color",
            field=models.CharField(
                default="text-cyan-400",
                help_text="Tailwind classes for reply icon color",
                max_length=100,
            ),
        ),
    ]
