# Generated by Django 5.0.14 on 2025-10-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0035_rename_timecolor_to_durationtextcolor"),
    ]

    operations = [
        migrations.AddField(
            model_name="chattheme",
            name="host_timestamp",
            field=models.CharField(
                default="text-xs opacity-60",
                help_text="Tailwind classes for host message timestamp (used with host_text for color)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="host_username",
            field=models.CharField(
                default="text-sm font-semibold",
                help_text="Tailwind classes for host username (used with host_text for color)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="my_timestamp",
            field=models.CharField(
                default="text-xs opacity-60",
                help_text="Tailwind classes for current user's message timestamp",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="my_username",
            field=models.CharField(
                default="text-xs font-semibold text-gray-400",
                help_text="Tailwind classes for current user's username",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="pinned_timestamp",
            field=models.CharField(
                default="text-xs opacity-60",
                help_text="Tailwind classes for pinned message timestamp (used with pinned_text for color)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="pinned_username",
            field=models.CharField(
                default="text-sm font-semibold",
                help_text="Tailwind classes for pinned message username (used with pinned_text for color)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="regular_timestamp",
            field=models.CharField(
                default="text-xs opacity-60",
                help_text="Tailwind classes for other users' message timestamp",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="regular_username",
            field=models.CharField(
                default="text-xs font-semibold text-gray-400",
                help_text="Tailwind classes for other users' usernames",
                max_length=200,
            ),
        ),
    ]
