# Generated by Django 5.0.14 on 2025-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0037_update_username_timestamp_to_white"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chattheme",
            name="my_timestamp",
            field=models.CharField(
                default="text-xs text-white opacity-60",
                help_text="Tailwind classes for current user's message timestamp",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="chattheme",
            name="my_username",
            field=models.CharField(
                default="text-xs font-semibold text-white",
                help_text="Tailwind classes for current user's username",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="chattheme",
            name="regular_timestamp",
            field=models.CharField(
                default="text-xs text-white opacity-60",
                help_text="Tailwind classes for other users' message timestamp",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="chattheme",
            name="regular_username",
            field=models.CharField(
                default="text-xs font-semibold text-white",
                help_text="Tailwind classes for other users' usernames",
                max_length=200,
            ),
        ),
    ]
