# Generated by Django 5.0.14 on 2025-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0040_apply_emerald_green_to_pinned_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name='chattheme',
            name='sticky_host_username',
            field=models.CharField(
                default='text-sm font-semibold text-white',
                help_text='Tailwind classes for host username in sticky area',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='sticky_pinned_username',
            field=models.CharField(
                default='text-sm font-semibold text-white',
                help_text='Tailwind classes for pinned message username in sticky area',
                max_length=200,
            ),
        ),
    ]
