# Generated by Django 5.0.14 on 2025-10-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0041_add_sticky_username_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name='chattheme',
            name='reply_preview_container',
            field=models.CharField(
                default='flex items-center justify-between px-4 py-2 bg-gray-100 dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700',
                help_text='Tailwind classes for reply preview container',
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='reply_preview_icon',
            field=models.CharField(
                default='w-4 h-4 flex-shrink-0 text-blue-500',
                help_text='Tailwind classes for reply preview icon',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='reply_preview_username',
            field=models.CharField(
                default='text-xs font-semibold text-gray-700 dark:text-gray-300',
                help_text='Tailwind classes for reply preview username',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='reply_preview_content',
            field=models.CharField(
                default='text-xs text-gray-600 dark:text-gray-400 truncate',
                help_text='Tailwind classes for reply preview message content',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='reply_preview_close_button',
            field=models.CharField(
                default='p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded',
                help_text='Tailwind classes for reply preview close button',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='reply_preview_close_icon',
            field=models.CharField(
                default='w-4 h-4 text-gray-500',
                help_text='Tailwind classes for reply preview close icon (X)',
                max_length=200,
            ),
        ),
    ]
