# Generated by Django 5.0.14 on 2025-10-10 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0042_add_reply_preview_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blocked_username",
                    models.CharField(
                        blank=True,
                        help_text="Case-insensitive username block",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "blocked_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Browser fingerprint block",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "blocked_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email block (future)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "blocked_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone block (future)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Optional note for host"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional: for timed blocks", null=True
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        help_text="Who created the block (usually host)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_created",
                        to="chats.chatparticipation",
                    ),
                ),
                (
                    "blocked_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered user account block",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="chats.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-blocked_at"],
                "indexes": [
                    models.Index(
                        fields=["chat_room", "blocked_username"],
                        name="chats_chatb_chat_ro_315033_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "blocked_fingerprint"],
                        name="chats_chatb_chat_ro_73b503_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "blocked_user"],
                        name="chats_chatb_chat_ro_0f92c8_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="chats_chatb_expires_13b38b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="chatblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blocked_username__isnull", False)),
                fields=("chat_room", "blocked_username"),
                name="unique_chat_username_block",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blocked_fingerprint__isnull", False)),
                fields=("chat_room", "blocked_fingerprint"),
                name="unique_chat_fingerprint_block",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("blocked_user__isnull", False)),
                fields=("chat_room", "blocked_user"),
                name="unique_chat_user_block",
            ),
        ),
    ]
