# Generated by Django 5.0.14 on 2025-10-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0043_add_message_reactions"),
        ("chats", "0043_chatblock_chatblock_unique_chat_username_block_and_more"),
    ]

    operations = []
