# Generated by Django 5.0.14 on 2025-10-13 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0044_merge_20251010_0529"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blocked_username",
                    models.CharField(
                        db_index=True,
                        help_text="Username being blocked (case-sensitive)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="messagereaction",
            new_name="chats_messa_message_470e59_idx",
            old_name="chats_messa_message_idx",
        ),
        migrations.RenameIndex(
            model_name="messagereaction",
            new_name="chats_messa_message_981da9_idx",
            old_name="chats_messa_message_user_idx",
        ),
        migrations.RenameIndex(
            model_name="messagereaction",
            new_name="chats_messa_message_7c36da_idx",
            old_name="chats_messa_message_finger_idx",
        ),
        migrations.AddField(
            model_name="userblock",
            name="blocker",
            field=models.ForeignKey(
                help_text="Registered user who is blocking",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userblock",
            index=models.Index(
                fields=["blocker", "blocked_username"],
                name="chats_userb_blocker_58b17f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userblock",
            unique_together={("blocker", "blocked_username")},
        ),
    ]
