# Generated by Django 5.0.14 on 2025-10-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0045_userblock_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatparticipation',
            index=models.Index(fields=['username'], name='chats_chatpart_username_global_idx'),
        ),
    ]
