# Generated by Django 5.0.14 on 2025-10-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0046_add_global_username_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatparticipation",
            name="chats_chatpart_username_global_idx",
        ),
        migrations.RemoveField(
            model_name="chatblock",
            name="blocked_email",
        ),
        migrations.RemoveField(
            model_name="chatblock",
            name="blocked_phone",
        ),
        migrations.AddField(
            model_name="chatblock",
            name="blocked_ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address for tracking (future: may be used for blocking)",
                null=True,
            ),
        ),
    ]
