# Generated by Django 5.0.14 on 2025-10-23 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0047_add_ip_tracking_to_chatblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatroom",
            name="chats_chatr_code_29f23d_idx",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "User-created (manual)"),
                    ("ai", "AI-generated (collaborative discovery)"),
                ],
                default="manual",
                help_text="How this room was created: manual (user) or ai (photo analysis)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="URL-safe room identifier (e.g., 'bar-room', 'roberts-storm-chasing-room')",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["code", "source"], name="chats_chatr_code_7ce957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["host", "code"], name="chats_chatr_host_id_270e28_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "manual")),
                fields=("host", "code"),
                name="unique_manual_room_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "ai")),
                fields=("code",),
                name="unique_ai_room_global",
            ),
        ),
    ]
