# Generated by Django 5.0.14 on 2025-11-01 17:30

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0048_add_chatroom_url_namespacing'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Embedding of room name for suggestion normalization (text-embedding-3-small, 1536d)', null=True),
        ),
    ]
