# Generated by Django 5.0.14 on 2025-11-04 20:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0049_chatroom_name_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Embedding of room name and description for suggestion normalization (text-embedding-3-small, 1536d)', null=True),
        ),
    ]
