# Generated by Django 5.0.14 on 2025-12-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0050_alter_chatroom_name_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='discovery_radius_miles',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum distance in miles for this chat to be discoverable', null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for location-based discovery', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for location-based discovery', max_digits=9, null=True),
        ),
    ]
