# Generated by Django 5.0.14 on 2025-12-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0051_add_location_discovery_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='pinned_until',
            new_name='sticky_until',
        ),
    ]
