# Generated by Django 5.0.14 on 2025-12-27 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0052_rename_pinned_until_to_sticky_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('banned_ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address ban', null=True)),
                ('banned_fingerprint', models.CharField(blank=True, db_index=True, help_text='Browser fingerprint ban', max_length=255, null=True)),
                ('reason', models.TextField(help_text='Reason for the ban')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the ban expires (null = permanent)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether ban is currently active')),
                ('banned_by', models.ForeignKey(help_text='Staff member who issued the ban', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_bans_issued', to=settings.AUTH_USER_MODEL)),
                ('banned_user', models.ForeignKey(blank=True, help_text='Registered user account ban', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Ban',
                'verbose_name_plural': 'Site Bans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['banned_user'], name='chats_siteb_banned__a46237_idx'), models.Index(fields=['banned_ip_address'], name='chats_siteb_banned__6f7dee_idx'), models.Index(fields=['banned_fingerprint'], name='chats_siteb_banned__b2c338_idx'), models.Index(fields=['is_active', 'expires_at'], name='chats_siteb_is_acti_dacbd8_idx')],
            },
        ),
    ]
