# Generated by Django 5.0.14 on 2025-12-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0053_add_site_ban_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattheme',
            name='my_host_username',
            field=models.CharField(default='text-sm font-semibold text-red-500', help_text="Tailwind classes for host's own username when viewing their own messages", max_length=200),
        ),
    ]
