# Generated by Django 5.0.14 on 2026-01-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0054_add_my_host_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='current_pin_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
