# Generated by Django 5.0.14 on 2026-01-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0055_add_current_pin_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattheme',
            name='reaction_highlight_bg',
            field=models.CharField(default='bg-zinc-700', help_text='Background classes for highlighted reaction pill', max_length=100),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='reaction_highlight_border',
            field=models.CharField(default='border border-zinc-500', help_text='Border classes for highlighted reaction pill', max_length=100),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='reaction_highlight_text',
            field=models.CharField(default='text-zinc-200', help_text='Text color classes for highlighted reaction count', max_length=100),
        ),
    ]
