# Generated by Django 5.0.14 on 2026-01-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0056_add_reaction_highlight_theme_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo_height',
            field=models.IntegerField(blank=True, help_text='Photo height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL to photo file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='photo_width',
            field=models.IntegerField(blank=True, help_text='Photo width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='video_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration of video in seconds', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='video_thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to video thumbnail image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video file', max_length=500, null=True),
        ),
    ]
