# Generated by Django 5.0.14 on 2026-02-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0057_add_photo_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattheme',
            name='avatar_border',
            field=models.CharField(blank=True, help_text="Optional border/ring classes (e.g., 'ring-2 ring-zinc-700')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='avatar_size',
            field=models.CharField(blank=True, help_text="Tailwind size classes for avatar (e.g., 'w-10 h-10'). Null = use Constance default", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='avatar_spacing',
            field=models.CharField(default='mr-3', help_text='Spacing between avatar and message content', max_length=50),
        ),
        migrations.AddField(
            model_name='chattheme',
            name='avatar_style',
            field=models.CharField(blank=True, help_text="DiceBear avatar style override (e.g., 'pixel-art', 'initials'). Null = use Constance default", max_length=50, null=True),
        ),
    ]
