# Generated by Django 5.0.14 on 2026-02-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0058_add_avatar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipation',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL to avatar image for this chat participation (stored in S3 or local storage)', max_length=500, null=True),
        ),
    ]
