# Generated by Django 5.0.14 on 2026-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0059_add_avatar_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video_height',
            field=models.IntegerField(blank=True, help_text='Video height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='video_width',
            field=models.IntegerField(blank=True, help_text='Video width in pixels', null=True),
        ),
    ]
