# Generated by Django 5.0.14 on 2026-02-18 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0060_message_video_height_message_video_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagereaction',
            name='unique_message_user_reaction',
        ),
        migrations.RemoveConstraint(
            model_name='messagereaction',
            name='unique_message_fingerprint_reaction',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chats_messa_message_981da9_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagereaction',
            name='chats_messa_message_7c36da_idx',
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'user', 'emoji'], name='chats_messa_message_7d9fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'fingerprint', 'emoji'], name='chats_messa_message_3cccfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('message', 'user', 'emoji'), name='unique_message_user_emoji_reaction'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('message', 'fingerprint', 'emoji'), name='unique_message_fingerprint_emoji_reaction'),
        ),
    ]
