# Generated by Django 5.0.14 on 2026-03-03 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0062_snapshot_dark_mode_remove_light_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier e.g. 'gift_coffee'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("emoji", models.CharField(help_text="Emoji character", max_length=10)),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "price_cents",
                    models.PositiveIntegerField(help_text="Price in cents"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food & Drink"),
                            ("fun", "Fun"),
                            ("love", "Love"),
                            ("animals", "Animals"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Soft-disable without removing"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering within category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift Catalog Item",
                "verbose_name_plural": "Gift Catalog Items",
                "ordering": ["category", "sort_order", "price_cents"],
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("host", "Host Message"),
                    ("system", "System Message"),
                    ("gift", "Gift Message"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("pin", "Message Pin"),
                    ("tip", "Tip to Host"),
                    ("gift", "Gift"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gift_id",
                    models.CharField(
                        help_text="Gift catalog ID at send time", max_length=50
                    ),
                ),
                ("emoji", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("price_cents", models.PositiveIntegerField()),
                ("sender_username", models.CharField(max_length=100)),
                ("recipient_username", models.CharField(max_length=100)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="chats.chatroom",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift",
                        to="chats.message",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gifts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gift_catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_gifts",
                        to="chats.giftcatalogitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_username", "chat_room", "is_acknowledged"],
                        name="chats_gift_recipie_bf46f2_idx",
                    ),
                    models.Index(
                        fields=["chat_room", "-created_at"],
                        name="chats_gift_chat_ro_8ebf26_idx",
                    ),
                ],
            },
        ),
    ]
