# Generated by Django 5.0.14 on 2026-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0063_giftcatalogitem_alter_message_message_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_gift_acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
