# Generated by Django 5.0.14 on 2026-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0065_fix_dark_mode_reply_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="gift_recipient",
            field=models.CharField(
                blank=True,
                help_text="Recipient username for gift messages (denormalized for filter indexing)",
                max_length=100,
                null=True,
            ),
        ),
    ]
