# Generated by Django 5.0.14 on 2026-03-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0066_add_gift_recipient_to_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipation",
            name="seen_intros",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Feature intros dismissed by anonymous user in this chat",
            ),
        ),
    ]
