# Generated by Django 5.0.14 on 2026-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0067_add_seen_intros"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chattheme",
            name="avatar_style",
        ),
        migrations.AddField(
            model_name="chattheme",
            name="emoji_picker_styles",
            field=models.JSONField(
                blank=True, default=dict, help_text="Styles for emoji reaction picker"
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="gift_styles",
            field=models.JSONField(
                blank=True, default=dict, help_text="Styles for gift message cards"
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="input_styles",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Styles for message input components",
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="modal_styles",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Styles for long-press modal and overlays",
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="ui_styles",
            field=models.JSONField(
                blank=True, default=dict, help_text="Styles for misc UI elements"
            ),
        ),
        migrations.AddField(
            model_name="chattheme",
            name="video_player_styles",
            field=models.JSONField(
                blank=True, default=dict, help_text="Styles for video player overlay"
            ),
        ),
        migrations.AlterField(
            model_name="chattheme",
            name="avatar_size",
            field=models.CharField(
                blank=True,
                help_text="Tailwind size classes for avatar (e.g., 'w-10 h-10'). Null = use default",
                max_length=50,
                null=True,
            ),
        ),
    ]
