# Postgres on RDS. Single-AZ db.t4g.small for dev. Master password is
# generated by Terraform, stored only in Secrets Manager — never logged
# to plan output (sensitive), never written to your shell history.

resource "random_password" "db_master" {
  length  = 32
  special = true
  # Avoid characters that need escaping in connection strings.
  override_special = "!#$%&*+-=?_"
}

resource "aws_secretsmanager_secret" "db_master" {
  name        = "${local.name_prefix}/rds/master"
  description = "Master credentials for the ChatPop dev RDS instance."

  # Allow re-creation under the same name without the 7-30 day name-recovery
  # window blocking us. Acceptable for dev; tighten for prod.
  recovery_window_in_days = 0
}

# ---------------------------------------------------------------------------
# Shared third-party API keys (OpenAI, Stripe, Google Places, etc.)
#
# Stored as a single JSON blob — keeps cost minimal and updates atomic.
# Terraform creates the secret container only; values are populated by:
#   chatpop admin import-env       (one-time migration from current .env)
#   chatpop admin set-secret KEY   (subsequent updates)
#
# Devs sync to .env via:
#   chatpop sync-secrets           (writes to backend/.env)
#
# Prod reads directly via boto3 — see backend/chatpop/settings.py.
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "api_keys" {
  name        = "${local.name_prefix}/api-keys"
  description = "Shared third-party API keys for ChatPop dev."

  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db_master" {
  secret_id = aws_secretsmanager_secret.db_master.id
  secret_string = jsonencode({
    username = var.db_master_username
    password = random_password.db_master.result
    engine   = "postgres"
    port     = 5432
    # host/dbname filled in after the instance exists; consumers can read
    # those from outputs or via DescribeDBInstances.
  })
}

# Custom parameter group: enforce SSL connections.
resource "aws_db_parameter_group" "postgres" {
  name        = "${local.display_prefix}-postgres"
  family      = "postgres16"
  description = "ChatPop dev - Postgres 16 with SSL required."

  parameter {
    name  = "rds.force_ssl"
    value = "1"
  }

  # See aws_db_subnet_group.dev — create new param group first so RDS can be
  # re-attached before the old gets destroyed.
  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_db_instance" "dev" {
  # Migrated from "chatpop-dev-postgres" via AWS CLI in-place rename. Code
  # updated to match so terraform refresh sees no diff. The chatpop-dev
  # name is gone from AWS — instance now lives at chatmie-dev-postgres.<…>.
  identifier = "${local.display_prefix}-postgres"

  # Engine
  engine               = "postgres"
  engine_version       = var.db_engine_version
  parameter_group_name = aws_db_parameter_group.postgres.name

  # Compute & storage
  instance_class        = var.db_instance_class
  allocated_storage     = var.db_allocated_storage
  max_allocated_storage = 100 # autoscale up to 100GB if filling up
  storage_type          = "gp3"
  storage_encrypted     = true

  # Network — private only, accessed via the Tailscale router
  publicly_accessible    = false
  db_subnet_group_name   = aws_db_subnet_group.dev.name
  vpc_security_group_ids = [aws_security_group.rds.id]

  # Initial database + master credentials
  db_name  = var.db_initial_database
  username = var.db_master_username
  password = random_password.db_master.result

  # Operational
  multi_az                   = false # dev: single-AZ to halve cost
  backup_retention_period    = var.db_backup_retention_days
  backup_window              = "08:00-09:00" # UTC
  maintenance_window         = "Sun:09:00-Sun:10:00"
  apply_immediately          = true # dev: don't wait for maintenance windows
  auto_minor_version_upgrade = true

  # Destruction safety: dev-friendly defaults. Prod would invert these.
  deletion_protection      = false
  skip_final_snapshot      = true
  delete_automated_backups = true

  # Performance Insights — free for the smallest tier (7 days retention).
  performance_insights_enabled          = true
  performance_insights_retention_period = 7

  tags = {
    Name = "${local.display_prefix}-postgres"
  }

  # The password lives in state (encrypted at rest in the local file) and
  # in Secrets Manager. Don't surface it in plan diffs.
  lifecycle {
    ignore_changes = [password]
  }
}
