/**
 * Demo theme configurations for landing page variations
 * Each theme has a unique dark color scheme
 */

export interface DemoTheme {
  id: number;
  name: string;
  background: string;
  headerBackground: string;
  titleGradient: string;
  badgeBackground: string;
  badgeText: string;
  buttonGradient: string;
  buttonHoverGradient: string;
  cardBackground: string;
  cardIconBackground: string;
  cardIconColor: string;
  themeColorLight: string;
  themeColorDark: string;
}

export const DEMO_THEMES: DemoTheme[] = [
  {
    id: 1,
    name: "Deep Ocean",
    background: "bg-[#404eed]",
    headerBackground: "bg-[#404eed]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#404eed",
    themeColorDark: "#404eed",
  },
  {
    id: 2,
    name: "Purple Night",
    background: "bg-[#5865f2]",
    headerBackground: "bg-[#5865f2]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#5865f2",
    themeColorDark: "#5865f2",
  },
  {
    id: 3,
    name: "Emerald Forest",
    background: "bg-[#23a55a]",
    headerBackground: "bg-[#23a55a]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#23a55a",
    themeColorDark: "#23a55a",
  },
  {
    id: 4,
    name: "Sunset Blaze",
    background: "bg-[#f23f43]",
    headerBackground: "bg-[#f23f43]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#f23f43",
    themeColorDark: "#f23f43",
  },
  {
    id: 5,
    name: "Royal Violet",
    background: "bg-[#9b59b6]",
    headerBackground: "bg-[#9b59b6]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#9b59b6",
    themeColorDark: "#9b59b6",
  },
  {
    id: 6,
    name: "Electric Blue",
    background: "bg-[#3498db]",
    headerBackground: "bg-[#3498db]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#3498db",
    themeColorDark: "#3498db",
  },
  {
    id: 7,
    name: "Rose Gold",
    background: "bg-[#eb459e]",
    headerBackground: "bg-[#eb459e]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#eb459e",
    themeColorDark: "#eb459e",
  },
  {
    id: 8,
    name: "Amber Glow",
    background: "bg-[#f39c12]",
    headerBackground: "bg-[#f39c12]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#f39c12",
    themeColorDark: "#f39c12",
  },
  {
    id: 9,
    name: "Midnight Teal",
    background: "bg-[#1abc9c]",
    headerBackground: "bg-[#1abc9c]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#1abc9c",
    themeColorDark: "#1abc9c",
  },
  {
    id: 10,
    name: "Crimson Dark",
    background: "bg-[#e74c3c]",
    headerBackground: "bg-[#e74c3c]/80",
    titleGradient: "from-white to-white",
    badgeBackground: "bg-white/10",
    badgeText: "text-white",
    buttonGradient: "from-white to-white",
    buttonHoverGradient: "from-gray-100 to-gray-100",
    cardBackground: "bg-white/5 border border-white/10",
    cardIconBackground: "bg-white/10",
    cardIconColor: "text-white",
    themeColorLight: "#e74c3c",
    themeColorDark: "#e74c3c",
  },
];
